export const clavePublica = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDqCu4CWPQSy/E7ECJ4AMDhkAev
HCK6owf8GTVnbGMdLadqRoLJEAboemDIdlbhs2IMBMsB8veCVCJcN13+I7hvbOlW
rUfNuEG8zkxsk4pDVEMgpxqZsPGXXa5TgJ1mGfI8KikrunpCVrPhNfFEI361Z3p9
i0AH7/Z4UydjOnGvwwIDAQAB
-----END PUBLIC KEY-----`;